// Generated by https://quicktype.io

export type SearchResult = {
  id: number;
  name: string;
  region: string;
  country: string;
  lat: number;
  lon: number;
  url: string;
};

export type SearchResponse = SearchResult[];
